---
- hosts: all 
  tasks:
    - name: Check connection
      ping:
      register: ping_output

    - name: Display connectivity
      debug:
        msg: "Successfully connected" 
      when: '"pong" == ping_output.ping' 

